version: '3.8'


services:
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
      - ./configs/alertmanager.yml:/etc/prometheus/alertmanager.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - 3001:3000
    depends_on:
      - loki
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server/
     - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
      
  mailcatcher:
    container_name: mailcatcher
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
    - "1080:1080"
    - "1025:1025"
    networks:
      - monitoring

  # app:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - ./configs/promtail-pm2-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/yalect/.pm2/logs:/var/.pm2/logs:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

volumes:
  prometheus_data: {}
  grafana-storage: {}


networks:
  monitoring:
    driver: bridge
